const DropdownActionTypes = {
    TOGGLE_ADMIN_DROPDOWN: 'TOGGLE_ADMIN_DROPDOWN',
    TOGGLE_MAP_DROPDOWN: 'TOGGLE_MAP_DROPDOWN',
    TOGGLE_SIGN_OUT: 'TOGGLE_SIGN_OUT',
    TOGGLE_NAVIGATION: 'TOGGLE_NAVIGATION'
};

export default DropdownActionTypes;
