const ArticlesActionTypes = {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
    POST_ARTICLE_START: 'POST_ARTICLE_START',
    POST_ARTICLE_SUCCESS: 'POST_ARTICLE_SUCCESS',
    POST_ARTICLE_FAILURE: 'POST_ARTICLE_FAILURE'
};

export default ArticlesActionTypes;