const ArticlesActionTypes = {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
    POST_ARTICLE_START: 'POST_ARTICLE_START',
    POST_ARTICLE_SUCCESS: 'POST_ARTICLE_SUCCESS',
    POST_ARTICLE_FAILURE: 'POST_ARTICLE_FAILURE',
    EDIT_ARTICLE_START: 'EDIT_ARTICLE_START',
    EDIT_ARTICLE_SUCCESS: 'EDIT_ARTICLE_SUCCESS',
    EDIT_ARTICLE_FAILURE: 'EDIT_ARTICLE_FAILURE',
    EDIT_DELETE_START: 'EDIT_DELETE_START',
    EDIT_DELETE_SUCCESS: 'EDIT_DELETE_SUCCESS',
    EDIT_DELETE_FAILURE: 'EDIT_DELETE_FAILURE'
};

export default ArticlesActionTypes;